name: LagSuite
version: '1.0.0'
main: net.scape.project.lagSuite.LagSuite
api-version: '1.13'
folia-supported: true

commands:
  lagsuite:
    description: Base command for LagSuite
    usage: /lagsuite <subcommand>