name: LagSuite
version: '${version}'
main: net.scape.project.lagSuite.LagSuite
api-version: '1.13'
folia-supported: true
softdepend:
  - ProtocolLib
commands:
  lagsuite:
    description: Base command for LagSuite
    usage: /lagsuite <subcommand>